version: "3.2"
services:

  sql-server-db:
    build: .
    restart: always
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - ./volume:/var/opt/mssql/data
    ports:
      - "2433:1433"
    environment:
      SA_PASSWORD: "your_secret"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
